[package]
name = "massa_metrics"
version = "0.25.0"
edition = "2021"

[features]
testing = []
sandbox = []

[dependencies]
prometheus = {workspace = true, "features" = ["process"]}
hyper = {workspace = true, "features" = ["server", "tcp", "http1"]}   # BOM UPGRADE     Revert to {"version": "0.14.26", "features": ["server", "tcp", "http1"]} if problem
tokio = {workspace = true, "features" = ["full"]}   # BOM UPGRADE     Revert to {"version": "1.28.0", "features": ["full"]} if problem
lazy_static = {workspace = true}
tracing = {workspace = true}
massa_channel = {workspace = true}
