[package]
name = "massa_executed_ops"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
nom = "=7.1"
rocksdb = "0.20"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
massa_models = { path = "../massa-models" }
massa_hash = { path = "../massa-hash" }
massa_serialization = { path = "../massa-serialization" }
massa_db = { path = "../massa-db" }

[dev-dependencies]
tempfile = "3.3"
massa_ledger_worker = { path = "../massa-ledger-worker" }