[package]
name = "massa_storage"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["massa_factory_exports/testing", "massa_metrics/testing"]

[dependencies]
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
massa_models = {workspace = true}
massa_metrics = {workspace = true}

[dev-dependencies]
massa_factory_exports = {workspace = true, "features" = ["testing"]}
massa_signature = {workspace = true}
