[package]
name = "massa_final_state"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["massa_ledger_worker/testing", "massa_async_pool/testing", "massa_pos_exports/testing"]
sandbox = ["massa_async_pool/sandbox"]
bootstrap_server = []

[dependencies]
displaydoc = {workspace = true}
serde = {workspace = true, "features" = ["derive"]}
nom = {workspace = true}
bs58 = {workspace = true, "features" = ["check"]}   # BOM UPGRADE     Revert to {"version": "0.4", "features": ["check"]} if problem
thiserror = {workspace = true}
tracing = {workspace = true}
num = {workspace = true}
massa_ledger_exports = {workspace = true}
massa_ledger_worker = {workspace = true, "optional" = true}
massa_executed_ops = {workspace = true}
massa_models = {workspace = true}
massa_async_pool = {workspace = true}
massa_serialization = {workspace = true}
massa_pos_exports = {workspace = true}
massa_db_exports = {workspace = true}
massa-proto-rs = {workspace = true, "features" = ["tonic"]}
massa_versioning = {workspace = true}
massa_time = {workspace = true}
massa_hash = {workspace = true}

[dev-dependencies]
massa_async_pool = {workspace = true, "features" = ["testing"]}
massa_ledger_worker = {workspace = true, "features" = ["testing"]}
massa_pos_worker = {workspace = true, "features" = ["testing"]}
massa_pos_exports = {workspace = true, "features" = ["testing"]}
massa_db_worker = {workspace = true}
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
tempfile = {workspace = true}   # BOM UPGRADE     Revert to "3.3" if problem
