[package]
name = "massa_pos_exports"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["crossbeam-channel", "massa_models/testing", "mockall"]

[dependencies]
bitvec = {workspace = true, "features" = ["serde"]}
displaydoc = {workspace = true}
nom = {workspace = true}
serde = {workspace = true, "features" = ["derive"]}
serde_json = {workspace = true}   # BOM UPGRADE     Revert to "1.0" if problem
thiserror = {workspace = true}
tracing = {workspace = true}
num = {workspace = true, "features" = ["serde"]}   # BOM UPGRADE     Revert to {"version": "0.4", "features": ["serde"]} if problem
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
crossbeam-channel = {workspace = true, "optional" = true}
mockall = {workspace = true, "optional" = true}   # BOM UPGRADE     Revert to {"version": "0.11.4", "optional": true} if problem
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_serialization = {workspace = true}
massa_signature = {workspace = true}
massa_db_exports = {workspace = true}

[dev-dependencies]
mockall = {workspace = true}
tempfile = {workspace = true}   # BOM UPGRADE     Revert to "3.3" if problem
massa_db_worker = {workspace = true}
