[[bench]]
name = "basic"
harness = false

[package]
name = "massa_execution_worker"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
sandbox = ["massa_async_pool/sandbox"]
gas_calibration = [
    "massa-sc-runtime/gas_calibration",
    "massa_execution_exports/gas_calibration",
    "massa_final_state/testing",
    "massa_pos_worker",
    "massa_ledger_worker",
    "massa_db_worker",
    "tempfile",
]
testing = [
    "massa_execution_exports/testing",
    "massa_ledger_exports/testing",
    "massa_pos_exports/testing",
    "massa_final_state/testing",
    "massa-sc-runtime/testing",
    "massa_wallet/testing",
    "tempfile",
    "massa_pos_worker",
    "massa_ledger_worker",
    "massa_metrics/testing",
    "massa_db_worker",
    "massa_metrics/testing",
]
benchmarking = [
    "massa-sc-runtime/gas_calibration",
    "criterion",
    "massa_pos_worker",
    "massa_ledger_worker",
    "massa_db_worker",
    "tempfile",
]
metrics = []

[dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }
bs58 = { workspace = true }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
parking_lot = { workspace = true, "features" = ["deadlock_detection"] }
tracing = { workspace = true }
serde_json = { workspace = true } # BOM UPGRADE     Revert to "1.0" if problem
num = { workspace = true, "features" = [
    "serde",
] } # BOM UPGRADE     Revert to {"version": "0.4", "features": ["serde"]} if problem
sha2 = { workspace = true }
sha3 = { workspace = true }
libsecp256k1 = { workspace = true }
criterion = { workspace = true, "optional" = true }
tempfile = { workspace = true, "optional" = true } # BOM UPGRADE     Revert to {"version": "3.3", "optional": true} if problem
massa_ledger_worker = { workspace = true, "optional" = true }
massa_pos_worker = { workspace = true, "optional" = true }
massa_async_pool = { workspace = true }
massa_channel = { workspace = true }
massa_executed_ops = { workspace = true }
massa_execution_exports = { workspace = true }
massa_models = { workspace = true }
massa_storage = { workspace = true }
massa_hash = { workspace = true }
massa-sc-runtime = { workspace = true }
massa_metrics = { workspace = true }
massa_module_cache = { workspace = true }
massa_serialization = { workspace = true }
massa_signature = { workspace = true }
massa_time = { workspace = true }
massa_ledger_exports = { workspace = true }
massa_pos_exports = { workspace = true }
massa_final_state = { workspace = true }
massa_versioning = { workspace = true }
massa_db_exports = { workspace = true }
massa_db_worker = { workspace = true, "optional" = true }
massa_wallet = { workspace = true }
massa-proto-rs = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, "features" = ["sync"] }
massa_pos_worker = { workspace = true }
massa_ledger_worker = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }                                          # BOM UPGRADE     Revert to "3.2" if problem
hex-literal = { workspace = true }
massa_execution_exports = { workspace = true, "features" = ["testing"] }
massa_final_state = { workspace = true, "features" = ["testing"] }
