[package]
name = "massa_xtask"
version = "0.23.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
massa_models = { path = "../massa-models" }
toml_edit = "0.19.8"
walkdir = "2.3.3"
