[package]
name = "massa_protocol_worker"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["massa_protocol_exports/testing", "tempfile", "massa_pool_exports/testing", "massa_consensus_exports/testing", "massa_metrics/testing"]

[dependencies]
tracing = {workspace = true, "features" = ["log"]}   # BOM UPGRADE     Revert to {"version": "0.1", "features": ["log"]} if problem
rand = {workspace = true}
parking_lot = {workspace = true}
crossbeam = {workspace = true}
serde_json = {workspace = true}   # BOM UPGRADE     Revert to "1.0" if problem
nom = {workspace = true}
num_enum = {workspace = true}
peernet = {workspace = true}
tempfile = {workspace = true, "optional" = true}   # BOM UPGRADE     Revert to {"version": "3.3", "optional": true} if problem
rayon = {workspace = true}
schnellru = {workspace = true}   # BOM UPGRADE     Revert to "0.2.1" if problem
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_logging = {workspace = true}
massa_channel = {workspace = true}
massa_protocol_exports = {workspace = true}
massa_consensus_exports = {workspace = true}
massa_metrics = {workspace = true}
massa_pool_exports = {workspace = true}
massa_pos_exports = {workspace = true}
massa_storage = {workspace = true}
massa_serialization = {workspace = true}
massa_signature = {workspace = true}
massa_time = {workspace = true}
massa_versioning = {workspace = true}

[dev-dependencies]
tempfile = {workspace = true}   # BOM UPGRADE     Revert to "3.3" if problem
serial_test = {workspace = true}   # BOM UPGRADE     Revert to "2.0.0" if problem
num = {workspace = true}
