[package]
name = "massa_pool_exports"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["crossbeam-channel"]

[dependencies]
serde = {workspace = true, "features" = ["derive"]}
tokio = {workspace = true, "features" = ["sync"]}
crossbeam-channel = {workspace = true, "optional" = true}
massa_models = {workspace = true}
massa_storage = {workspace = true}
massa_time = {workspace = true}
massa_pos_exports = {workspace = true}
massa_execution_exports = {workspace = true}

[dev-dependencies]
