[package]
name = "massa_serialization"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]

[dependencies]
displaydoc = {workspace = true}
thiserror = {workspace = true}
nom = {workspace = true}
unsigned-varint = {workspace = true, "features" = ["nom"]}
num = {workspace = true}
