[package]
name = "massa_ledger_exports"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["tempfile", "massa_models/testing"]

[dependencies]
displaydoc = {workspace = true}
serde = {workspace = true, "features" = ["derive"]}
serde_json = {workspace = true}   # BOM UPGRADE     Revert to "1.0" if problem
tempfile = {workspace = true, "optional" = true}   # BOM UPGRADE     Revert to {"version": "3.3", "optional": true} if problem
thiserror = {workspace = true}
nom = {workspace = true}
num_enum = {workspace = true}   # BOM UPGRADE     Revert to "0.5.10" if problem
massa-proto-rs = {workspace = true, "features" = ["tonic"]}
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_serialization = {workspace = true}
massa_db_exports = {workspace = true}
