[package]
name = "massa_factory_worker"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
sandbox = []
testing = ["massa_factory_exports/testing", "massa_pos_exports/testing", "massa_pool_exports/testing", "massa_protocol_exports/testing", "massa_wallet/testing"]

[dependencies]
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
crossbeam-channel = {workspace = true}
tracing = {workspace = true}
massa_channel = {workspace = true}
massa_models = {workspace = true}
massa_factory_exports = {workspace = true}
massa_serialization = {workspace = true}
massa_signature = {workspace = true}
massa_storage = {workspace = true}
massa_time = {workspace = true}
massa_wallet = {workspace = true}
massa_hash = {workspace = true}
massa_pos_exports = {workspace = true}
massa_pool_exports = {workspace = true}
massa_versioning = {workspace = true}

[dev-dependencies]
num = {workspace = true}
massa_protocol_exports = {workspace = true, "features" = ["testing"]}
massa_consensus_exports = {workspace = true, "features" = ["testing"]}
massa_factory_exports = {workspace = true, "features" = ["testing"]}
massa_wallet = {workspace = true, "features" = ["testing"]}
massa_pos_exports = {workspace = true, "features" = ["testing"]}
massa_pool_exports = {workspace = true, "features" = ["testing"]}
