[package]
name = "massa_pool_worker"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["massa_pool_exports/testing", "massa_execution_exports/testing", "massa_pos_exports/testing", "massa_wallet/testing"]

[dependencies]
tracing = {workspace = true}
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
massa_models = {workspace = true}
massa_storage = {workspace = true}
massa_pool_exports = {workspace = true}
massa_time = {workspace = true}
massa_wallet = {workspace = true}

[dev-dependencies]
tokio = {workspace = true, "features" = ["sync"]}
mockall = {workspace = true}
massa_signature = {workspace = true}
massa_hash = {workspace = true}
massa_pos_exports = {workspace = true, "features" = ["testing"]}
massa_pool_exports = {workspace = true, "features" = ["testing"]}
massa_execution_exports = {workspace = true, "features" = ["testing"]}
crossbeam-channel = {workspace = true}
