[package]
name = "massa_wallet"
version = "0.25.0"
edition = "2021"

[features]
testing = ["tempfile", "massa_models/testing"]

[dependencies]
displaydoc = {workspace = true}
serde = {workspace = true, "features" = ["derive"]}
serde_json = {workspace = true}   # BOM UPGRADE     Revert to "1.0" if problem
serde_qs = {workspace = true}
thiserror = {workspace = true}
tempfile = {workspace = true, "optional" = true}   # BOM UPGRADE     Revert to {"version": "3.3", "optional": true} if problem
massa_cipher = {workspace = true}
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_signature = {workspace = true}
