[package]
name = "massa_grpc"
version = "0.25.0"
edition = "2021"
description = "GRPC API for Massa Blockchain"
repository = "https://github.com/massalabs/massa/"
homepage = "https://massa.net"
documentation = "https://docs.massa.net/"

[dependencies]
massa-proto-rs = {workspace = true, "features" = ["tonic"]}
displaydoc = {workspace = true}
thiserror = {workspace = true}
tonic = {workspace = true, "features" = ["gzip", "tls"]}
tonic-web = {workspace = true}
tonic-reflection = {workspace = true}
tonic-health = {workspace = true}
tower-http = {workspace = true, "features" = ["cors"]}
hyper = {workspace = true}
futures-util = {workspace = true}
serde = {workspace = true, "features" = ["derive"]}
tokio = {workspace = true, "features" = ["rt-multi-thread", "macros"]}
tokio-stream = {workspace = true}   # BOM UPGRADE     Revert to "0.1.12" if problem
tracing = {workspace = true}
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
itertools = {workspace = true}
h2 = {workspace = true}

massa_consensus_exports = {workspace = true}
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_pos_exports = {workspace = true}
massa_pool_exports = {workspace = true}
massa_protocol_exports = {workspace = true}
massa_execution_exports = {workspace = true}
massa_storage = {workspace = true}
massa_time = {workspace = true}
massa_wallet = {workspace = true}
massa_serialization = {workspace = true}
massa_versioning = {workspace = true}
massa_signature = {workspace = true}
massa_bootstrap = {workspace = true}

[dev-dependencies]
num = {workspace = true}
massa_consensus_exports = {workspace = true, "features" = ["testing"]}
massa_channel = {workspace = true}
