[package]
name = "massa_pos_worker"
version = "0.25.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
sandbox = []
testing = ["massa_pos_exports/testing"]

[dependencies]
parking_lot = {workspace = true, "features" = ["deadlock_detection"]}
rand = {workspace = true}   # BOM UPGRADE     Revert to "=0.8.5" if problem
rand_distr = {workspace = true}
rand_xoshiro = {workspace = true}   # BOM UPGRADE     Revert to "=0.6" if problem
tracing = {workspace = true}
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_pos_exports = {workspace = true}

[dev-dependencies]
massa_pos_exports = {workspace = true, "features" = ["testing"]}
