[package]
name = "massa_pos_worker"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
rand = "=0.8.5"                                     
rand_distr = "=0.4.3"                              
rand_xoshiro = "=0.6"
tracing = "0.1"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_pos_exports = { path = "../massa-pos-exports" }

[dev-dependencies]
# custom modules with testing enabled
massa_pos_exports = { path = "../massa-pos-exports", features = ["testing"] }

[features]
sandbox = []
testing = ["massa_pos_exports/testing"]
