[package]
name = "massa_consensus_worker"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4", features = ["serde"] }
tracing = { version = "0.1", features = ["log"] }
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
#custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }

[dev-dependencies]
rand= "0.8"
itertools = "0.10"

[features]
sandbox = []
bootstrap_server = []
